### PR TITLE
[AUT-282] Test against concrete error cases

### PR DESCRIPTION
**Pull request by misolubarda**

### CODE REVIEW

**Review by maxstubbersfield — COMMENTED** [review]
Did you also want to change the file names as well?

**Comment by maxstubbersfield** [comment]
Would you please be able to increment the version?

**Comment by misolubarda** [comment]
> Did you also want to change the file names as well?

Ah of course

**Comment by misolubarda** [comment]
> Would you please be able to increment the version?

Sure

**Review by maxstubbersfield — APPROVED** [review]

**Pull request merged**
